import { memo, useMemo } from "react";
import { motion } from "framer-motion";
import { AlertCircle, TrendingDown, BookX, Building2 } from "lucide-react";
import { useStudents } from "@/context/StudentsContext";

export const KeyRiskInsights = memo(() => {
    const { students } = useStudents();

    if (!students.length) return null;

    // 1. Attendance Insight
    const lowAttendance = students.filter(s => s.attendance < 50);
    const lowAttRiskRate = lowAttendance.length > 0
        ? lowAttendance.filter(s => s.predicted_risk_probability >= 0.6).length / lowAttendance.length
        : 0;

    const okAttendance = students.filter(s => s.attendance >= 50);
    const okAttRiskRate = okAttendance.length > 0
        ? okAttendance.filter(s => s.predicted_risk_probability >= 0.6).length / okAttendance.length
        : 1;

    const attMultiplier = okAttRiskRate > 0 ? (lowAttRiskRate / okAttRiskRate).toFixed(1) : "Multiple";

    // 2. Backlog Insight
    const withBacklogs = students.filter(s => s.backlog_count >= 1);
    const withoutBacklogs = students.filter(s => s.backlog_count === 0);

    const backlogRiskRate = withBacklogs.length > 0
        ? (withBacklogs.filter(s => s.predicted_risk_probability >= 0.6).length / withBacklogs.length) * 100
        : 0;

    const noBacklogRiskRate = withoutBacklogs.length > 0
        ? (withoutBacklogs.filter(s => s.predicted_risk_probability >= 0.6).length / withoutBacklogs.length) * 100
        : 0;

    const backlogDiff = Math.max(0, Math.round(backlogRiskRate - noBacklogRiskRate));

    // 3. Department Insight
    const courses: Record<string, { total: number; highRisk: number }> = {};
    students.forEach(s => {
        if (!courses[s.course]) courses[s.course] = { total: 0, highRisk: 0 };
        courses[s.course].total++;
        if (s.predicted_risk_probability >= 0.6) courses[s.course].highRisk++;
    });

    let maxRiskDept = "N/A";
    let maxRiskRatio = 0;
    Object.entries(courses).forEach(([course, data]) => {
        if (data.total > 5) { // Minimum sample size
            const ratio = data.highRisk / data.total;
            if (ratio > maxRiskRatio) {
                maxRiskRatio = ratio;
                maxRiskDept = course;
            }
        }
    });

    const insights = [
        {
            icon: TrendingDown,
            color: "text-risk-high bg-risk-high/10",
            text: <>Students with <strong>{"<50% attendance"}</strong> are <strong>{attMultiplier}x</strong> more likely to be high-risk.</>
        },
        {
            icon: BookX,
            color: "text-orange-500 bg-orange-500/10",
            text: <>Having <strong>1 or more backlogs</strong> correlates with a <strong>{backlogDiff}% higher</strong> dropout probability.</>
        },
        {
            icon: Building2,
            color: "text-risk-medium bg-risk-medium/10",
            text: <>The <strong>{maxRiskDept}</strong> department currently has the highest concentration of high-risk students.</>
        },
        {
            icon: AlertCircle,
            color: "text-blue-400 bg-blue-400/10",
            text: <>A consistent <strong>GPA decline after Semester 3</strong> is a leading indicator for increased risk.</>
        }
    ];

    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.15, duration: 0.5, ease: "easeOut" }}
            className="glass-card p-6"
        >
            <div className="flex items-center gap-2 mb-5">
                <div className="p-1.5 rounded-lg bg-primary/10">
                    <AlertCircle className="w-4 h-4 text-primary" />
                </div>
                <h2 className="text-lg font-semibold font-display text-foreground">Key Risk Insights</h2>
                <span className="text-xs text-muted-foreground ml-auto bg-secondary/50 px-2 py-1 rounded-md hidden sm:inline-block">Auto-Generated by ML</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {insights.map((insight, i) => (
                    <motion.div
                        key={i}
                        initial={{ opacity: 0, x: -10 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: 0.2 + (i * 0.1) }}
                        className="flex items-start gap-3 p-4 rounded-xl bg-secondary/30 border border-secondary/50"
                    >
                        <div className={`p-2 rounded-lg shrink-0 ${insight.color}`}>
                            <insight.icon className="w-4 h-4" />
                        </div>
                        <p className="text-sm text-muted-foreground leading-relaxed mt-0.5">
                            {insight.text}
                        </p>
                    </motion.div>
                ))}
            </div>
        </motion.div>
    );
});
KeyRiskInsights.displayName = "KeyRiskInsights";
